repos:
  # Unit tests with Poetry
  - repo: local
    hooks:
      - id: pytest-unit
        name: Run unit tests
        entry: poetry run pytest tests/unit
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-commit]

  # Code formatting with Black
  - repo: https://github.com/psf/black
    rev: 23.11.0
    hooks:
      - id: black
        language_version: python3.12

  # Import sorting with isort
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        language_version: python3.12
        args: ["--profile", "black"]

  # Type checking with mypy
  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v1.7.0
  #   hooks:
  #     - id: mypy
  #       language_version: python3.12
  #       additional_dependencies: [types-PyYAML, types-requests]
  #       args: [--ignore-missing-imports]
